# https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow
name: "Test: Erlang/OTP v21.3"
on: push
jobs:
  checks:
    name: checks
    runs-on: ubuntu-18.04
    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-elixir
      - name: CONFIGURE OTP & ELIXIR
        uses: actions/setup-elixir@v1
        with:
          otp-version: 21.3
          # https://github.com/elixir-lang/elixir/releases
          elixir-version: 1.8.0
      - name: CHECK RABBITMQ COMPONENTS
        # https://github.community/t5/GitHub-Actions/How-can-I-set-an-expression-as-an-environment-variable-at/m-p/41804/highlight/true#M4751
        id: ref
        run: |
          branch_or_tag_name=${GITHUB_REF#refs/*/}
          echo "::set-output name=branch_or_tag_name::$branch_or_tag_name"
          make check-rabbitmq-components.mk base_rmq_ref=master current_rmq_ref=$branch_or_tag_name
      - name: CHECK SCRIPTS
        run: |
          make bats base_rmq_ref=master current_rmq_ref=${{ steps.ref.outputs.branch_or_tag_name }}
      # https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows
      - name: CACHE DEPS
        uses: actions/cache@v1
        with:
          path: deps
          key: otp-21.3_git-${{ github.sha }}_deps
      - name: RESOLVE & COMPILE DEPS
        run: |
          make deps test-deps base_rmq_ref=master current_rmq_ref=${{ steps.ref.outputs.branch_or_tag_name }}
          echo "Capture versions of the RabbitMQ components used in this workflow..."
          make rabbit-rabbitmq-deps.mk
          mv rabbit-rabbitmq-deps.mk deps/
          echo "Remove directories not used in the subsequent jobs..."
          rm -fr deps/*/{.git,test}
      - name: UPLOAD DEPS VERSIONS
        uses: actions/upload-artifact@v2-preview
        with:
          name: rabbit-rabbitmq-deps.mk
          path: deps/rabbit-rabbitmq-deps.mk
      - name: CHECK CROSS REFERENCES
        run: |
          make xref base_rmq_ref=master current_rmq_ref=${{ steps.ref.outputs.branch_or_tag_name }}
      - name: COMPILE FOR TEST
        run: |
          make test-build base_rmq_ref=master current_rmq_ref=${{ steps.ref.outputs.branch_or_tag_name }}
      - name: CLONE SECONDARY UMBRELLA
        #if: 'oldest' == 'oldest'
        uses: actions/checkout@v2
        with:
          repository: rabbitmq/rabbitmq-public-umbrella
          path: umbrellas/master
      - name: PREPARE SECONDARY UMBRELLA COPIES
        if: 'oldest' == 'oldest'
        run: |
          make -C umbrellas/master fetch-deps
          # TODO: Determine the right list of release branches to have
          # for this master.
          for branch in v3.8.x v3.7.x; do
            if test 'master' = "$branch"; then
              # When testing on the same release branch, we use the oldest
              # tag.
              version=$(git -C umbrellas/master/deps/rabbit tag -l $(echo ${branch%.x}).* | \
                grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
            else
              # When testing against an older release branch, we use the
              # latest tag.
              version=$(git -C umbrellas/master/deps/rabbit tag -l $(echo ${branch%.x}).* | \
                grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | tail -n 1)
            fi
            test "$version"
            umbrella="umbrella/$version"
            # We copy the master Umbrella and checkout the appropriate tag.
            cp -a umbrellas/master "$umbrella"
            make -C "$umbrella" up BRANCH="$version"
          done
      - name: CACHE SECONDARY UMBRELLAS
        if: 'oldest' == 'oldest'
        uses: actions/cache@v1
        with:
          path: umbrellas
          key: git-${{ github.sha }}_secondary_umbrellas
  eunit:
    needs: [checks]
    # https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#contexts
    name: eunit
    runs-on: ubuntu-18.04
    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-elixir
      - name: CONFIGURE OTP & ELIXIR
        uses: actions/setup-elixir@v1
        with:
          otp-version: 21.3
          # https://github.com/elixir-lang/elixir/releases
          elixir-version: 1.8.0
      - name: CACHE DEPS
        uses: actions/cache@v1
        with:
          path: deps
          key: otp-21.3_git-${{ github.sha }}_deps
      - name: RUN TESTS
        run: |
          ! test -d ebin || touch ebin/*
          branch_or_tag_name=${GITHUB_REF#refs/*/}
          make eunit base_rmq_ref=master current_rmq_ref=$branch_or_tag_name FULL=
  capture-tested-deps-versions:
    needs:
      - eunit
    runs-on: ubuntu-18.04
    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v2
      - name: CACHE DEPS
        uses: actions/cache@v1
        with:
          path: deps
          key: otp-21.3_git-${{ github.sha }}_deps
      - name: FORMAT GIT REF
        # https://github.community/t5/GitHub-Actions/How-can-I-set-an-expression-as-an-environment-variable-at/m-p/41804/highlight/true#M4751
        id: ref
        run: |
          branch_or_tag_name=${GITHUB_REF#refs/*/}
          echo "::set-output name=branch_or_tag_name::$branch_or_tag_name"
      - name: UPLOAD TO S3
        if: github.ref == 'refs/heads/master'
        # https://github.com/marketplace/actions/s3-file-upload
        uses: zdurham/s3-upload-github-action@master
        env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: ${{ secrets.AWS_REGION }}
         FILE: deps/rabbit-rabbitmq-deps.mk
         S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
         S3_KEY: rabbitmq-server/${{ steps.ref.outputs.branch_or_tag_name }}/${{ github.run_id }}/otp-21.3/rabbit-rabbitmq-deps.mk
